version: '3.1'

services:

  api:
    build: .
    ports:
      - "8082:8082"

  mirth-connect:
    image: nextgenhealthcare/connect:3.9.1
    ports:
      - "8081:8080" # Mirth Administrator
      - "8444:8443" # Port HTTPS (si vous utilisez SSL)
    volumes:
      - ./mirth-data:/opt/mirth-connect/appdata # Persister les données de configuration et les logs
      - ./hl7-files:/mnt/hl7_files # Dossier pour les fichiers HL7 entrants
      - ./output-files:/mnt/output_files # Dossier pour les fichiers JSON sortants (facultatif)
    restart: unless-stopped
